# Generated by Django 3.2.4 on 2022-11-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('total_spaces', models.IntegerField()),
                ('available_spaces', models.IntegerField()),
            ],
        ),
    ]
